# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_USER: sanchez
      MYSQL_PASSWORD: 2365
      MYSQL_ROOT_PASSWORD: 2365
      MYSQL_DATABASE: topic
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_container
    restart: always
    ports:
      - "1025:1025"  # Puerto SMTP
      - "8025:8025"  # Interfaz web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
